### ISSUE TITLE
License issue with Forge 35.1.29

### ISSUE THREAD

**Issue by alexandzors** [abused/Industrial-Meat#4]
When Industrial Meat is loaded with Forge 35.1.29 the game fails to load because IM is missing license information in `mods.toml`. 

Adding any type of license information into `mods.toml` fixes it.

**Comment by alothmanmoe** [comment]
Huh, didn't think forge required a license to be specified. But it's no problem I'll add one in with the next update for 1.16.4

**Comment by alexandzors** [comment]
no problem! figured I'd let you know.
