### ISSUE TITLE
mekanism and industrial meat are crashing the game

### ISSUE THREAD

**Issue by dokimiki** [abused/Industrial-Meat#5]
### Issue description

The game crashes when Mekanism's energy is sent to the Meat Packer(industrialmeat:meat_packer).

### Steps to reproduce

1. Place the Meat Packer(industrialmeat:meat_packer)
2. Place a block next to the Meat Packer where the mekanism can transmit power(e.g. Basic Universal Cable(mekanism:basic universal_cable))

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.33

### Industrial Meet version

1.16.5-1.0.4

### Other relevant versions

Mekanism 1.16.5 10.1.2

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/dokimiki/66e1c538ef49acc913844159dda77a8e

Translate by deepl.com

**Comment by justliliandev** [comment]
This is caused by 
https://github.com/abused/Industrial-Meat/blob/1.16/src/main/java/abused_master/industrialmeat/tileentity/TileEntityMeatPacker.java#L194
as this method doesn't follow the contract of Nonnull and Mekanism Cables first try to look for StrictEnergy/FluxNetworks EnergyCapability
